collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.395056
color:
  saturation: 0.2350681677926332
  brandStrength: 0.522388
  lightness: 0.2139332049991935
  brandColors:
    - '#C2BDB9'
    - '#2D2824'
    - '#4E4945'
    - '#6E6965'
    - '#8F8A86'
  rhythmicContrast: 0.2203274285420775
layout_spectrum: 0.4594216
name: JulianFoster
