collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.395056
color:
  saturation: 0.2350681677926332
  brandStrength: 0.3969629439525306
  lightness: 0.2139332049991935
  brandColors:
    - '#010101'
    - '#D33E9C'
    - '#314215'
    - '#E5B4A6'
    - '#BF8B75'
  rhythmicContrast: 0.2203274285420775
layout_spectrum: 0.4594216
name: JulianFoster
