collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.395056
color:
  saturation: 0.4216418
  brandStrength: 0.522388
  lightness: 1
  brandColors:
    - '#C2BDB9'
    - '#2D2824'
    - '#4E4945'
    - '#6E6965'
    - '#8F8A86'
  rhythmicContrast: 0.2304104
layout_spectrum: 0.4594216
name: JulianFoster
